serve:
	ipython nbconvert human_control_param_id.ipynb --to slides --template slides_reveal.tpl --post serve
build:
	ipython nbconvert human_control_param_id.ipynb --to slides --template slides_reveal.tpl
